const JSONClasses = {
  "Theme-default": {
    id: "defaultId",
    themeHeaderColor: "Egate_logo_with_Link",
    themeSubContainer: "Egate_landing_header-e6578i",
    themeLogoImgC: "Egate_logo_hjurnfh",
    themeBranchBox: "EGATE_elandUl-pg_Default",
    theme_landing_branch_box_btns: "default_landing_branch_box_btns",
    themeLogoImg: "defaultLogoImg",
    themeLandingParentContainer: "EGATE_landingE",
    themeLCapImgDiv: "Egate_loge_landing",
    themeCapTextContainer: "defaultCapTextContainer",
    themeTextContainer: "Egate_landiing_ojnkl",
    themeBranchesContainer: "Egate_eLanding_Container_Egate_landing",
    themeBranchesSubContainer: "EGATE_eCordsLanding",
    themeLanding_branch_box_btns: "Pg_buttonn_Default_Cards",
    themeBranchBoxEntranceExam: "themeBranchBoxEntranceExam_Default",
    themeLanding_branch_box_Exams_Container: "EGATE_elandUl",
    themeExamImageBox: "ug_pg_boxes",
    themeExamButtonsBox: "Exams_container",
    themeUgAndPgButtons: "ugAndPgButtonsDefault",

    //About Us div class
    themeAboutuscontainer: "container",
    themeLogoImgC: "Ug_header_Container",
    themeLogoImg: "Ug_header_logoIMG",
    themeAboutusmaindiv: "",
    themeHeadingtext: "abus_heading",
    themeAboutusimg: "image-section",
    themeAboutegtmaindiv: "text-section",
    themeAboutegtdiv: "about_egt",
    themeAboutusmaindiv: "info-section",
    themeAboutusmaindivinfo: "info_out",
    themeAboutusinfobox: "info-box",
    themeAboutusprofileimg: "profile-img",

    // For practicing Div structure fromate for footer section //

    ThemeFooterMainContainer: "ThemeFooterMainContainerDefault",
    ThemeFooterSubContainer: "ThemeFooterSubContainerDefault",
    ThemeFooterSubContainerFirstPart: "ThemeFooterSubContainerFirstPartDefault",
    ThemeFooterSubContainerSecondtPart:
      "ThemeFooterSubContainerSecondtPartDefault",
    ThemeFooterSubContainerFirstPartEGATEData:
      "ThemeFooterSubContainerFirstPartEGATEDataDefault",
    ThemeFooterSubContainerFirstPartLinksData:
      "ThemeFooterSubContainerFirstPartLinksDataDefault",
    ThemeFooterSubContainerSecondtPartContactUsData:
      "ThemeFooterSubContainerSecondtPartContactUsDataDefault",
    ThemeFooterSubContainerCopywriteData:
      "ThemeFooterSubContainerCopywriteDataDefault",
    ThemeFooterHorizantalLine: "ThemeFooterHorizantalLineDefault",

    // End //
    // our courses
    themeExtraPCForFeatures: "DefaultthemeExtraPCForFeatures",
    themeFeaturesHeading: "DeaultthemeFeaturesHeading",
    themeArrowWithFeatures: "DefaultthemeArrowWithFeatures",
    themeFeatures: "DefaultthemeFeatures",
    // Footer classes
    themeFooterMainContainer: "themeFooterMainContainerDeafult",
    themeFooterSubContainer: "themeFooterSubContainerDefault",
    themeFooterContentMainContainer: "themeFooterContentMainContainerDefault",
    themeFooterFirstContentContainer: "themeFooterFirstContentContainerDefault",
    themeFootereGRADTtutoContent: "themeFootereGRADTtutoContentDefault",
    themeFooterFirstContent: "themeFooterFirstContentDefault",
    themeFooterLinksContent: "themeFooterLinksContentDefault",
    themeFooterContactUsContent: "themeFooterContactUsContentDefault",
    themeFooterContactData: "themeFooterContactDataDefault",
    themeFooterCopywriteContentContainer:
      "themeFooterCopywriteContentContainerDefault",

    themeFooterCopywriteContent: "themeFooterCopywriteContentDefault",
    // 
    themeMainFooterContainer:"t1MainFooterContainer",
    themeInnerMainFooterContainer:"t1InnerMainFooterContainer",
    themeInnerMainFooterContentContainer:"t1InnerMainFooterContentContainer",
    themeInnerMainFooterContentColumnContainer:"t1InnerMainFooterContentColumnContainer",
   
 
    // themeFooterMainContainer:"t1FooterMainContainer",
    // themeFooterSubContainer:"t1FooterSubContainer",
    // themeFooterContentMainContainer:"t1FooterContentMainContainer",
    // themeFooterFirstContentContainer:"t1FooterFirstContentContainer",
    // themeFootereGRADTtutoContent:"t1FootereGRADTtutoContent",
    // themeFooterFirstContent:"t1FooterFirstContent",
    // themeFooterLinksContent:"t1FooterLinksContent",
    // themeFooterContactUsContent:"t1FooterContactUsContent",
    // themeFooterContactData:"t1FooterContactData",
    // themeFooterCopywriteContentContainer:"t1FooterCopywriteContentContainer",
    // themeContactFooterContentContainer:"t1ContactFooterContentContainer",
  },
  "Theme-1": {
    id: "themeOneId",
    themeHeaderColor: "t1HeaderColor",
    themeSubContainer: "t1SubContainer",
    themeLogoImgC: "t1ThemeLogoImgC",
    themeBranchBox: "t1BranchBox",
    theme_landing_branch_box_btns: "t1Llanding_branch_box_btns",
    themeLogoImg: "t1LogoImg",
    themeLandingParentContainer: "t1LandingParentContainer",
    themeLCapImgDiv: "t1LCapImgDiv",
    themeCapTextContainer: "t1CapTextContainer",
    themeTextContainer: "t1TextContainer",
    themeBranchesContainer: "t1BranchesContainer",
    themeBranchesSubContainer: "t1BranchesSubContainer",
    themeExamButtonsBox: "t1ExamButtonsBox",
    themeExamImageBox: "t1ExamImageBox",
    themeLanding_branch_box_btns: "t1Landing_branch_box_btns",
    themeLanding_branch_box_li_buttons: "t1Landing_branch_box_li_buttons",

    themeAboutuscontainer: "t1container",
    // themeLogoImgC: "Ug_header_Container",
    // themeLogoImg: "Ug_header_logoIMG",
    // themeAboutusmaindiv: "",
    themeHeadingtext: "t1abus_heading",
    themeAboutusimg: "t1image-section",
    themeAboutegtmaindiv: "t1text-section",
    themeAboutegtdiv: "t1about_egt",
    themeAboutusmaindiv: "t1info-section",
    themeAboutusmaindivinfo: "t1info_out",
    themeAboutusinfobox: "t1info-box",
    themeAboutusprofileimg: "t1profile-img",
    themeUgAndPgButtons: "t1UgAndPgButtons",
    //  new div structure for landing page
    theme1welcomecontainer: "theme1welcomecontainer",
    theme1UGEntranceExamsContainer: "theme1UGEntranceExamsContainer",
    themeInBranchBox: "themeInBranchBox",
    themeMainFooterContainer:"t1MainFooterContainer",
    themeInnerMainFooterContainer:"t1InnerMainFooterContainer",
    themeInnerMainFooterContentContainer:"t1InnerMainFooterContentContainer",
    themeInnerMainFooterContentColumnContainer:"t1InnerMainFooterContentColumnContainer",
   
 
    themeFooterMainContainer:"t1FooterMainContainer",
    themeFooterSubContainer:"t1FooterSubContainer",
    themeFooterContentMainContainer:"t1FooterContentMainContainer",
    themeFooterFirstContentContainer:"t1FooterFirstContentContainer",
    themeFootereGRADTtutoContent:"t1FootereGRADTtutoContent",
    themeFooterFirstContent:"t1FooterFirstContent",
    themeFooterLinksContent:"t1FooterLinksContent",
    themeFooterContactUsContent:"t1FooterContactUsContent",
    themeFooterContactData:"t1FooterContactData",
    themeFooterCopywriteContentContainer:"t1FooterCopywriteContentContainer",
    themeContactFooterContentContainer:"t1ContactFooterContentContainer",
  },
  "Theme-2": {
    id: "themeTwoId",
    themeHeaderColor: "t2HeaderColor",
    themeSubContainer: "t2SubContainer",
    themeLogoImgC: "t2ThemeLogoImgC",
    themeBranchBox: "t2BranchBox",
    theme_landing_branch_box_btns: "t2Landing_branch_box_btns",
    themeLogoImg: "t2LogoImg",
    themeLandingParentContainer: "t2LandingParentContainer",
    themeLCapImgDiv: "t2LCapImgDiv",
    themeCapTextContainer: "t2CapTextContainer",
    themeTextContainer: "t2TextContainer",
    themeBranchesContainer: "t2BranchesContainer",
    themeBranchesSubContainer: "t2BranchesSubContainer",
    themeExamImageBox: "t2ExamImageBox",
    themeLanding_branch_box_btns: "t2Landing_branch_box_btns",
    themeExamButtonsBox: "t2ExamButtonsBox",
    themeUgAndPgButtons: "t2UgAndPgButtons",
    themeUg: "ugHomeFromJSON",
    themeUgHeaderLi: "t2UgHeaderLi",
    themeUgHomeContainer: "t2UgHomeContainer",
    themeUgHeaderSec: "t2UgHeaderSec",
    themeUgHeaderContainer: "t2UgHeaderContainer",
    themeUgHeaderLogoImg: "t2UgHeaderLogoImg",
    themeUgHeaderUl: "t2UgHeaderUl",
    themeMarqData: "t2MarqData",
    // for footer, json classes
    themeFooterMainContainer: "t2FooterMainContainer",
    themeFooterSubContainer: "t2FooterSubContainer",
    themeFooterContentMainContainer: "t2FooterContentMainContainer",
    themeFooterFirstContentContainer: "t2FooterFirstContentContainer",
    themeFootereGRADTtutoContent: "t2FootereGRADTtutoContent",
    themeFooterFirstContent: "t2FooterFirstContentD",
    themeFooterLinksContent: "t2FooterLinksContent",
    themeFooterContactUsContent: "t2FooterContactUsContent",
    themeFooterContactData: "t2FooterContactData",
    themeFooterCopywriteContentContainer:
      "t2FooterCopywriteContentContainer",

    themeFooterCopywriteContent: "t2FooterCopywriteContent",
  },
};
export default JSONClasses;
