import AboutUs from "../../EgradTutorFrontEnd/EgradTutorWebsit/WebsiteSubPages/AboutUsPage/AboutUs";

const JSONClasses = {
  "Theme-default": {
    id: "defaultId",
    themeHeaderColor: "Egate_logo_with_Link",
    themeSubContainer: "Egate_landing_header-e6578i",
    themeLogoImgC: "Egate_logo_hjurnfh",
    themeBranchBox: "EGATE_elandUl-pg_Default",
    theme_landing_branch_box_btns: "default_landing_branch_box_btns",
    themeLogoImg: "defaultLogoImg",
    themeLandingParentContainer: "EGATE_landingE",
    themeLCapImgDiv: "Egate_loge_landing",
    themeCapTextContainer: "defaultCapTextContainer",
    themeTextContainer: "Egate_landiing_ojnkl",
    themeBranchesContainer: "Egate_eLanding_Container_Egate_landing",
    themeBranchesSubContainer: "EGATE_eCordsLanding",
    themeLanding_branch_box_btns: "Pg_buttonn_Default_Cards",
    themeBranchBoxEntranceExam: "themeBranchBoxEntranceExam_Default",
    themeLanding_branch_box_Exams_Container: "EGATE_elandUl",
    themeExamImageBox: "ug_pg_boxes",
    themeExamButtonsBox: "Exams_container",
    themeUgAndPgButtons: "ugAndPgButtonsDefault",
    ThemeExamADD_EDIT_Buttons: "ThemeExamADD_EDIT_ButtonsDefault",

    // UG_HOME_PAGE_HEADER_CLASSESS
    themeUgHomePageFirstContainer: "defaultUgHomePageFirstContainer",
    themeUgHomeContainer: "themeUgHomeContainerDefault",
    themeUgHeaderSec: "themeUgHeaderSecDefault",
    themeUgHeaderContainer: "themeUgHeaderContainerDefault",
    themeUgHeaderLogoImg: "themeUgHeaderLogoImgDefault",
    themeUgDivLinksOfHeader: "themeUgDivLinksOfHeaderDefault",

    // UG_HOME_PAGE_NAVBAR_CLASSES
    themeUgHeader: "themeUgHeaderDefault",
    themeUgHContainer: "themeUgHContainerDefault",
    themeUgNavContainer: "themeUgNavContainerDefault",
    themeUgHeaderUl: "themeUgHeaderUlDefault",
    themeUgHeaderLi: "themeUgHeaderLiDefault",
    themeMarqData: "themeMarqDataDefault",

    // EXPLORE EXAMS CLASSES
    themeExploreExamsMainContainer: "themeExploreExamsMainContainerDefault",
    themeExploreExamsSubContainer: "themeExploreExamsSubContainerDefault",
    themeNewExploreExams_ExamCard_MainContainer:
      "NewExploreExams_ExamCard_ContainerDefault",
    themeNewExploreExams_ExamCard_Container:
      "NewExploreExams_ExamCard_ContainerDefault",
    themeNewExploreExams_ExamName_Container:
      "NewExploreExams_ExamName_ContainerDefault",
    themeNewExploreExams_PortalNames_Container:
      "NewExploreExams_PortalNames_ContainerDefault",
    NewExploreExams_Image_Container: "NewExploreExams_Image_ContainerDefault",
    themeNewExploreExams_EachCard_Container:
      "NewExploreExams_EachCard_ContainerDefault",
    themeNewExploreExams_Exam_Container:
      "themeNewExploreExams_Exam_ContainerDefault",
    themeNewExploreExams_Image: "themeNewExploreExams_ImageDefault",
    //About Us div class
    themeAboutuscontainer: "container",
    themeHeadingtext: "abus_heading",
    themeAboutusimg: "image-section",
    themeAboutegtmaindiv: "text-section",
    themeAboutegtdiv: "about_egt",
    themeAboutusmaindiv: "info-section",
    themeAboutusmaindivinfo: "info_out",
    themeAboutusinfobox: "info-box",
    themeAboutusprofileimg: "profile-img",
    // Div structure fromate for footer section //
    ThemeFooterMainContainer: "ThemeFooterMainContainerDefault",
    ThemeFooterSubContainer: "ThemeFooterSubContainerDefault",
    ThemeFooterSubContainerFirstPart: "ThemeFooterSubContainerFirstPartDefault",
    ThemeFooterSubContainerSecondtPart:
      "ThemeFooterSubContainerSecondtPartDefault",
    ThemeFooterSubContainerFirstPartEGATEData:
      "ThemeFooterSubContainerFirstPartEGATEDataDefault",
    ThemeFooterSubContainerFirstPartLinksData:
      "ThemeFooterSubContainerFirstPartLinksDataDefault",
    ThemeFooterSubContainerSecondtPartContactUsData:
      "ThemeFooterSubContainerSecondtPartContactUsDataDefault",
    ThemeFooterSubContainerCopywriteData:
      "ThemeFooterSubContainerCopywriteDataDefault",
    ThemeFooterHorizantalLine: "ThemeFooterHorizantalLineDefault",
    // our courses container
    themeOurCoursesContainer: "defaltOurCoursesContainer",
    themeCoursesHeadding: "defaultCoursesHeadding",
    themeCoursesSubContainer: "defaultCoursesSubContainer",
    themeCoursesUl: "defaultCoursesUl",
    themeCourseLi: "defaultCourseLi",
    themePortalName: "defaultPortalName",
    themeExamsNames: "defaultExamsNames",
    themeCFeatures: "defaultCFeatures",
    themeFeaturesContainer: "defaultFeaturesContainer",
    themeFeatures: "defaultFeatures",
    themeFeatureImgC: "defaultFeatureImgC",
    themeCoursesBoxContainer: "themeCoursesBoxContainerDefault",
    themeCourseName: "defaultCourseName",
    themeFeaturesSecondContainer: "defaultFeaturesSecondContainer",
    themeFeaturesToBeRow: "defaultFeaturesToBeRow",
    themeCoursePortalNameImageContainer:
      "themeCoursePortalNameImageContainerDefault",
    // End //
    themeExamPageHeaderMainContainer: "themeExamPageHeaderMainContainer",
    themeExamPageHeaderContainer: "themeExamPageHeaderContainer",
    themeExamPageHeaderHeading: "themeExamPageHeaderHeading",
    themeTotalExamContainer: "themeTotalExamContainer",
    themeLinkToSpecificExam: "defaultLinkToSpecificExam",
    // exam page classes
    themeExamInfoMainContainer: "defaultExamInfoMainContainer",
    themeExamInfoBtnsContainer: "defaultExamInfoBtnsContainer",
    themeExamInfoSubContainer: "defaultExamInfoSubContainer",
    themeExamInfoBtns: "defaultExamInfoBtns",
    themeExamInfoDivs: "defaultExamInfoDivs",
    themeExamInfoToggles: "defaultExamInfoToggles",
    themeToggles: "defaultToggles",
    themeExamCoursesContainer: "defaultExamCoursesContainer",
    themeExamCoursesSubContainer: "defaultExamCoursesSubContainer",
    themeExamCoursesNameHeading: "defaultExamCoursesNameHeading",
    themePortalNames: "defaultPortalNames",
    themeExamPortalBtn: "defaultExamPortalBtn",
    themeExamPortalImgDivInCard: "defaultExamPortalImgDivInCard",

    // Footer classes
    themeFooterMainContainer: "themeFooterMainContainerDeafult",
    themeFooterSubContainer: "themeFooterSubContainerDefault",
    themeFooterContentMainContainer: "themeFooterContentMainContainerDefault",
    themeFooterFirstContentContainer: "themeFooterFirstContentContainerDefault",
    themeFootereGRADTtutoContent: "themeFootereGRADTtutoContentDefault",
    themeFooterFirstContent: "themeFooterFirstContentDefault",
    themeFooterLinksContent: "themeFooterLinksContentDefault",
    themeFooterContactUsContent: "themeFooterContactUsContentDefault",
    themeFooterContactData: "themeFooterContactDataDefault",
    themeFooterCopywriteContentContainer:
      "themeFooterCopywriteContentContainerDefault",

    themeFooterCopywriteContent: "themeFooterCopywriteContentDefault",
    themeFooterSMIcons: "themeFooterSMIconsDefault",

    // our courses
    themeExtraPCForFeatures: "DefaultthemeExtraPCForFeatures",
    themeFeaturesHeading: "DeaultthemeFeaturesHeading",
    themeArrowWithFeatures: "DefaultthemeArrowWithFeatures",
    // themeFeatures: "DefaultthemeFeatures",

    // AboutUs Clsses
    AboutUsMainContainer: "AboutUsMainContainerDefault",
    AboutUsImgContainer: "AboutUsImgContainerDefault",
    AboutUsContentMainContainer: "AboutUsContentMainContainerDefault",
    AboutUs1stContentContainer: "AboutUs1stContentContainerDefault",
    AboutUsImgDataContentContainer: "AboutUsImgDataContentContainerDefault",
    AboutUsVisionContentContainer: "AboutUsVisionContentContainerDefault",
    AboutUsContentSubContainer: "AboutUsContentSubContainerDefault",

    // Contact Us classes
    themeContactUsMainContainer: "themeContactUsMainContainerDefault",
    ContactUsContentDataContainer: "ContactUsContentDataContainerDefault",
    ContactUsMapContainer: "ContactUsMapContainerDefault",
    ContactUsMapData: "ContactUsMapDataDefault",
    ContactUsContentContainer: "ContactUsContentContainerDefault",
    ContactUsDataContainer: "ContactUsDataContainerDefault",
    ContactUsFormContainer: "ContactUsFormContainerDefault",
    ContactUsFormData: "ContactUsFormDataDefault",

    ContactUsFormFirstName: "ContactUsFormFirstNameDefault",
    ContactUsFormLasttName: "ContactUsFormLasttNameDefault",
    ContactUsFormemail: "ContactUsFormemailDefault",
    ContactUsFormCategory: "ContactUsFormCategoryDefault",
    ContactUsForMessage: "ContactUsForMessageDefault",

    // Links page classes
    LinksPagesMainContainer: "LinksPagesMainContainerDefault",
    AboutUsImgContainer: "AboutUsImgContainerDefault",
    LinksDataContainer: "LinksDataContainerDefault",
    // Faq classes
    FaqMainContainer: "FaqMainContainerDefault",
    FaqSubContainer: "FaqSubContainerDefault",
    FaqDataContainer: "FaqDataContainerDefault",
    FaqData: "FaqDataDefault",

    // courses page json classses from previousely did theme
    // which was theme white
    theme_COURSES: "whiteCOURSES",
    themeSectionContainer: "whiteSectionContainer",
    themeHeader: "whiteHeader",
    themeContant: "whiteContant",
    themeContainer: "whiteContainer",
    theme_courses_container: "white_courses_container",
    // headerComponent: <Theme_GreenHeader />,
    themeCards: "whiteCards",
    themeLogin_btn: "white_login_btn",
    theme_Dropdownmenu: "white_Dropdownmenu",
    themeMainPageNavbar: "whiteThemeMainPageNavbar",
    theam_NavContant: "white_NavContant",
    theme_portal: "white_portal",
    theme_examName: "white_examName",
    theme_exam_group: "white_exam_group",
    themeCard: "whiteCard",
    themeCardImg: "whiteImgDiv",
    themeCardBody: "whiteCardBody",
    themeCourseInfoSpan: "whiteThemeCourseInfo",
    themeCourseNameInCard: "whiteCourseNameInCard",
    themeParentContainer: "whiteParentContainer",
    themeWCUContainer: "whiteWCUContainer",
    themeIconsAndCardsPC: "whiteIconsAndCardsPC",
    themeIconsAndCards: "whiteIconAndCards",
    themetransparent_bg: "theme_transparent_bg",
    themescrolled_bg: "theme_scrolled_bg",
    themeswhite_Logins: "white_themesLogins",
    themeswhite_LoginsContainer: "themeswhite_LoginsContainer",

    // COURSEPAGE HEADER CSS

    CoursePageHeaderContainer: "CoursePageHeaderContainerDefault",
    themeLogoImgC: "themeLogoImgCDefault",
    logoC: "logoCDefault",
    CoursePageItemsContainer: "CoursePageItemsContainerDefault",
    themeCourseAmountSpan: "themeCourseAmountSpanDefault",

    // Popular Courses 
    themePopularCourses_container:"themePopularCourses_containerDefault",
    themePopularCourses_Subcontainer:"themePopularCourses_SubcontainerDefault",
    themeCourseheader_continer:"themeCourseheader_continerDefault",
    theme_COURSES:"theme_COURSES",
    themeBuyCourseSpan:"themeBuyCourseSpanDefault",
    themeHeadingInCp:"HeadingInCp_default",

    themeTabsDivMainContainer:"themeTabsDivMainContainerDefault",
    themeTabsDiv:"themeTabsDivDefault",
    themeTabsSubContainer:"themeTabsSubContainerDefault",
    themeTabsButtonContainer:"themeTabsButtonContainerDefault",
    themeTabButtonUl:"themeTabButtonUlDefault",
    themeSelectedTabContentDiv:"themeSelectedTabContentDivDefault",
    themeTabsChange:"themeTabsChangeDefault",
    themeTabDetailsDiv:"themeTabDetailsDivDefault",
    themeTabDetailsSubDiv:"themeTabDetailsSubDivDefault",
    themeTabImageDiv:"themeTabImageDivDefault",
    themeTabContentDiv:"themeTabContentDivDefault",
    themeBuyButtonInCP:"defaultBuyButtonInCP",
    themeTabContentSplittedText:"defaultTabContentSplittedText",

  },

  "Theme-1": {
    id: "themeOneId",
    themeHeaderColor: "t1HeaderColor",
    themeSubContainer: "t1SubContainer",
    themeLogoImgC: "t1ThemeLogoImgC",
    themeBranchBox: "t1BranchBox",
    theme_landing_branch_box_btns: "t1Llanding_branch_box_btns",
    themeLogoImg: "t1LogoImg",
    themeLandingParentContainer: "t1LandingParentContainer",
    themeLCapImgDiv: "t1LCapImgDiv",
    themeCapTextContainer: "t1CapTextContainer",
    themeTextContainer: "t1TextContainer",
    themeBranchesContainer: "t1BranchesContainer",
    themeBranchesSubContainer: "t1BranchesSubContainer",
    themeExamButtonsBox: "t1ExamButtonsBox",
    themeExamImageBox: "t1ExamImageBox",
    themeLanding_branch_box_btns: "t1Landing_branch_box_btns",
    themeLanding_branch_box_li_buttons: "t1Landing_branch_box_li_buttons",

    themeAboutuscontainer: "t1container",
    // themeLogoImgC: "Ug_header_Container",
    // themeLogoImg: "Ug_header_logoIMG",
    // themeAboutusmaindiv: "",
    themeHeadingtext: "t1abus_heading",
    themeAboutusimg: "t1image-section",
    themeAboutegtmaindiv: "t1text-section",
    themeAboutegtdiv: "t1about_egt",
    themeAboutusmaindiv: "t1info-section",
    themeAboutusmaindivinfo: "t1info_out",
    themeAboutusinfobox: "t1info-box",
    themeAboutusprofileimg: "t1profile-img",
    themeUgAndPgButtons: "t1UgAndPgButtons",

    // footer classes added by shiva
    ThemeFooterMainContainer: "t1FooterMainContainer",
    ThemeFooterSubContainer: "t1FooterSubContainer",
    ThemeFooterSubContainerFirstPart: "t1FooterSubContainerFirstPart",
    ThemeFooterSubContainerSecondtPart: "t1FooterSubContainerSecondtPart",
    ThemeFooterSubContainerFirstPartEGATEData:
      "t1FooterSubContainerFirstPartEGATEData",
    ThemeFooterSubContainerFirstPartLinksData:
      "t1FooterSubContainerFirstPartLinksData",
    ThemeFooterSubContainerSecondtPartContactUsData:
      "t1FooterSubContainerSecondtPartContactUsData",
    ThemeFooterSubContainerCopywriteData: "t1FooterSubContainerCopywriteData",
    ThemeFooterHorizantalLine: "t1FooterHorizantalLine",

    themeUgHeaderLi: "t1UgHeaderLi",
    themeUgHomeContainer: "t1UgHomeContainer",
    themeUgHeaderSec: "t1UgHeaderSec",
    themeUgHeaderContainer: "t1UgHeaderContainer",
    themeUgHeaderLogoImg: "t1UgHeaderLogoImg",
    themeUgHeaderUl: "t1UgHeaderUl",
    themeMarqData: "t1MarqData",
    themeUgDivLinksOfHeader: "t1UgDivLinksOfHeader",
    themeUgHeader: "t1UgHeader",
    themeUgNavContainer: "t1UgNavContainer",
    themeUgHContainer: "t1UgHContainer",
    themeUgExploreExamsContainer: "t1UgExploreExamsContainer",
    themeUgExploreExamsSection: "t1UgExploreExamsSection",
    themeUgExploreExamsContent: "t1UgExploreExamsContent",

    // ug our courses part
    themeCoursesHeaddings: "t1CoursesHeadding",
    themeCoursesSubContainers: "t1CoursesSubContainer",
    themeCoursesUls: "t1CoursesUl",
    themeCourseLis: "t1CourseLi",
    themePortalNamess: "t1PortalName",
    themeExamsNamess: "t1ExamsNames",
    themeArrowWithFeaturess: "themeArrowWithFeatures",
    themeFeaturesContainers: "t1FeaturesContainer",
    themeFeaturesHeadings: "t1FeaturesHeading",
    themeFeaturess: "t1Features",
    themeFeatureImgCs: "t1FeatureImgC",
    themeExtraPCForFeaturess: "t1ExtraPCForFeatures",
    themeCourseNamess: "t1CourseName",
    themeFeaturesSecondContainers: "t1FeaturesSecondContainer",

    // themeCFeatures: "t1CFeatures",
    // themeFeaturesContainer: "t1FeaturesContainer",
    // themeOurCoursesContainers: "t1OurCoursesContainer",
    // themeFeaturesToBeRow: "t1FeaturesToBeRow",

    themeExamPageHeaderMainContainer: "t1ExamPageHeaderMainContainer",
    themeExamPageHeaderContainer: "t1ExamPageHeaderContainer",
    themeExamPageHeaderHeading: "t1ExamPageHeaderHeading",
    themeTotalExamContainer: "t1TotalExamContainer",
    themeExamInfoMainContainer: "t1ExamInfoMainContainer",
    themeExamInfoBtnsContainer: "t1ExamInfoBtnsContainer",
    themeExamInfoSubContainer: "t1ExamInfoSubContainer",
    themeExamInfoBtns: "t1ExamInfoBtns",
    themeExamInfoDivs: "t1ExamInfoDivs",
    themeExamInfoToggles: "t1ExamInfoToggles",
    themeToggles: "t1Toggles",
    themeUgHomePageFirstContainer: "t1UgHomePageFirstContainer",
    themeExamCoursesContainer: "t1ExamCoursesContainer",
    themeExamCoursesSubContainer: "t1ExamCoursesSubContainer",
    themeExamCoursesNameHeading: "t1ExamCoursesNameHeading",
    themePortalNames: "t1PortalNames",
    themeExamPortalBtn: "t1ExamPortalBtn",
    // EXPLORE EXAM CLASSES
    themeExploreExamsMainContainer: "t1ExploreExamsMainContainer",
    themeExploreExamsSubContainer: "t1ExploreExamsSubContainer",
    themeNewExploreExams_ExamCard_MainContainer:
      "t1NewExploreExams_ExamCard_Container",
    themeNewExploreExams_ExamCard_Container:
      "t1NewExploreExams_ExamCard_Container",
    themeNewExploreExams_ExamName_Container:
      "t1NewExploreExams_ExamName_Container",
    themeNewExploreExams_PortalNames_Container:
      "t1NewExploreExams_PortalNames_Container",
    themeNewExploreExams_Image: "t1NewExploreExams_Image_Container",
    themeNewExploreExams_EachCard_Container:
      "t1NewExploreExams_EachCard_Container",
    themeLinkToSpecificExam: "t1LinkToSpecificExam",
    themeCoursePortalNameImageContainer: "t1CoursePortalNameImageContainer",
    themeFeaturesHeading: "t1FeaturesHeading",
    themeArrowWithFeatures: "t1ArrowWithFeatures",
    themeExploreImgContainer: "t1ExploreImgContainer",
    // themeFeatures: "t2Features",
    themeExamPortalImgDivInCard: "t1ExamPortalImgDivInCard",
    // extra class for theme1

    // exam info for exam page

    theme1welcomecontainer: "theme1welcomecontainer",
    theme1UGEntranceExamsContainer: "theme1UGEntranceExamsContainer",
    themeInBranchBox: "themeInBranchBox",

    themeMainFooterContainer: "t1MainFooterContainer",
    themeInnerMainFooterContainer: "t1InnerMainFooterContainer",
    themeInnerMainFooterContentContainer: "t1InnerMainFooterContentContainer",
    themeInnerMainFooterContentColumnContainer:
      "t1InnerMainFooterContentColumnContainer",

    themeFooterMainContainer: "t1FooterMainContainer",
    themeFooterSubContainer: "t1FooterSubContainer",
    themeFooterContentMainContainer: "t1FooterContentMainContainer",
    themeFooterFirstContentContainer: "t1FooterFirstContentContainer",
    themeFootereGRADTtutoContent: "t1FootereGRADTtutoContent",
    themeFooterFirstContent: "t1FooterFirstContent",
    themeFooterLinksContent: "t1FooterLinksContent",
    themeFooterContactUsContent: "t1FooterContactUsContent",
    themeFooterContactData: "t1FooterContactData",
    themeFooterCopywriteContentContainer: "t1FooterCopywriteContentContainer",
    themeContactFooterContentContainer: "t1ContactFooterContentContainer",
    themeFooterCopyrightData: "t1FooterCopyrightData",
    themeFooterCopyrightWrapperData: "t1FooterCopyrightWrapperData",
    themeFooterCopyrightTextData: "t1FooterCopyrightTextData",
    themeFooterContentColumn: "t1FooterContentColumn",

    // ABOUT US//
    themeAboutUsMainsContainer: "t1AboutUsMainsContainer",
    themeAUSection1: "t1AUSection1",
    AboutUsImgContainer: "t1AboutUsImgContainer",
    themeAboutUsImgWithTextDiv: "t1AboutUsImgWithTextDiv",
    themeAUHeadingContainer: "t1AUHeadingContainer",
    AboutUsContentMainContainer: "t1AboutUsContentMainContainer",
    AboutUs1stContentContainer: "t1AboutUs1stContentContainer",
    AboutUsImgDataContentContainer: "t1AboutUsImgDataContentContainer",
    themeAboutusFlexDiv: "t1AboutusFlexDiv",
    themeAboutusFlexDivForImg: "t1AboutusFlexDivForImg",
    AboutUsContentSubContainer: "t1AboutUsContentSubContainer",
    AboutUsVisionContentContainer: "t1AboutUsVisionContentContainer",
    AboutUsImgDataContentContainer: "t1AboutUsImgDataContentContainer",
    VMissionImgs: "t1VMissionImgs",
    VMissionContainer: "t1VMissionContainer",

    // contact us
    themeContactusMainsContainer: "t1ContactusMainsContainer",
    themeContactUsSubbMainContainer: "t1ContactUsSubbMainContainer",
    themeContactUsContentsDataContainer: "t1ContactUsContentsDataContainer",
    themeContactsUsMapContainer: "t1ContactsUsMapContainer",
    themeContactUsMapData: "t1ContactUsMapData",
    themeContactUsFormAndAdressContainer: "t1ContactUsFormAndAdressContainer",
    themeContactUsContentContainer: "t1ContactUsContentContainer",
    themeContactUsDataContainer: "t1ContactUsDataContainer",
    themeContactUsFormContainer: "t1ContactUsFormContainer",
    themeContactUsFormData: "t1ContactUsFormData",
    themeContactUsFormsFirstName: "t1ContactUsFormsFirstName",
    themeContactUsFormsLasttName: "t1ContactUsFormsLasttName",
    themeContactsUsFormemail: "t1ContactsUsFormemail",
    themeContactUsFormCategory: "t1ContactUsFormCategory",
    // courses classes data classes from previously did theme-green
    id: "quizHomeGreen",
    theme_COURSES: "greenCOURSES",
    themeSectionContainer: "greenSectionContainer",
    themeHeader: "greenHeader",
    themeContant: "greenContant",
    themeContainer: "greenContainer",
    theme_courses_container: "Gr_courses_container",
    // headerComponent: <Theme_GreenHeader />,
    themeCards: "greenCards",
    themeLogin_btn: "green_login_btn",
    theme_Dropdownmenu: "green_Dropdownmenu",
    themeMainPageNavbar: "greenThemeMainPageNavbar",
    theam_NavContant: "green_NavContant",
    theme_portal: "green_portal green_portal2",
    theme_examName: "green_examName",
    theme_exam_group: "green_exam_group",
    themeCard: "greenCard",
    themeCardImg: "greenImgDiv",
    themeCardBody: "greenCardBody",
    themeCourseInfoSpan: "greenThemeCourseInfo",
    themeCourseNameInCard: "greenCourseNameInCard",
    themeParentContainer: "greenParentContainer",
    themeWCUContainer: "greenWCUContainer",
    themeIconsAndCardsPC: "greenIconsAndCardsPC",
    themeIconsAndCards: "greenIconAndCards",

    // link classes
    LinksPagesMainContainer: "t1LinksPagesMainContainer",
    AboutUsImgContainer: "t1AboutUsImgContainer",
    LinksDataContainer: "t1LinksDataContainer",

    // FAQ classes
    tFaqMainContainer: "t1FaqMainContainer",
    AboutUsImgContainer: "t1AboutUsImgContainer",
    FaqSubContainer: "t1FaqSubContainer",
    FaqDataContainer: "t1FaqDataContainer",
    FaqData: "t1FaqData",

    // Popular Courses 
    CoursePageHeaderContainer:"t1CoursePageHeaderContainer",
    themeCoursePageHeaderContainer:"t1CoursePageHeaderContainer",
    themeCPHeaderUl:"t1CPHeaderUl",
    themePopularCourses_container:"t1PopularCourses_container",
    themePopularCourses_Subcontainer:"t1PopularCourses_Subcontainer",
    themeCourseheader_continer:"t1Courseheader_continer",
    theme_COURSES:"t1_COURSES",
    themeBuyCourseSpan:"t1BuyCourseSpan",
    themeHeadingInCp:"t1HeadingInCp",

    themeTabsDivMainContainer:"t1TabsDivMainContainer",
    themeTabsDiv:"t1TabsDiv",
    themeTabsSubContainer:"t1TabsSubContainer",
    themeTabsButtonContainer:"t1TabsButtonContainer",
    themeTabButtonUl:"t1TabButtonUl",
    themeSelectedTabContentDiv:"t1SelectedTabContentDiv",
    themeTabsChange:"t1TabsChange",
    themeTabDetailsDiv:"t1TabDetailsDiv",
    themeTabDetailsSubDiv:"t1TabDetailsSubDiv",
    themeTabImageDiv:"t1TabImageDiv",
    themeTabContentDiv:"t1TabContentDiv",
    themeBuyButtonInCP:"t1BuyButtonInCP",
    themeTabContentSplittedText:"t1TabContentSplittedText",
    themeTabContentSplittedTextInDiv:"t1TabContentSplittedTextInDiv",

  },
  "Theme-2": {
    id: "themeTwoId",
    themeHeaderColor: "t2HeaderColor",
    themeSubContainer: "t2SubContainer",
    themeLogoImgC: "t2ThemeLogoImgC",
    themeBranchBox: "t2BranchBox",
    theme_landing_branch_box_btns: "t2Landing_branch_box_btns",
    themeLogoImg: "t2LogoImg",
    themeLandingParentContainer: "t2LandingParentContainer",
    themeLCapImgDiv: "t2LCapImgDiv",
    themeCapTextContainer: "t2CapTextContainer",
    themeTextContainer: "t2TextContainer",
    themeBranchesContainer: "t2BranchesContainer",
    themeBranchesSubContainer: "t2BranchesSubContainer",
    themeExamImageBox: "t2ExamImageBox",
    themeLanding_branch_box_btns: "t2Landing_branch_box_btns",
    themeExamButtonsBox: "t2ExamButtonsBox",
    themeUgAndPgButtons: "t2UgAndPgButtons",
    themeUg: "ugHomeFromJSON",
    themeUgHeaderLi: "t2UgHeaderLi",
    themeUgHomeContainer: "t2UgHomeContainer",
    themeUgHeaderSec: "t2UgHeaderSec",
    themeUgHeaderContainer: "t2UgHeaderContainer",
    themeUgHeaderLogoImg: "t2UgHeaderLogoImg",
    themeUgHeaderUl: "t2UgHeaderUl",
    themeMarqData: "t2MarqData",
    themeUgDivLinksOfHeader: "t2UgDivLinksOfHeader",
    themeUgHeader: "themeUgHeader",
    themeUgNavContainer: "themeUgNavContainer",
    themeUgHContainer: "themeUgHContainer",
    themeUgExploreExamsContainer: "t2UgExploreExamsContainer",
    themeUgExploreExamsSection: "t2UgExploreExamsSection",
    themeUgExploreExamsContent: "t2UgExploreExamsContent",

    themeExamPageHeaderMainContainer: "t2ExamPageHeaderMainContainer",
    themeExamPageHeaderContainer: "t2ExamPageHeaderContainer",
    themeExamPageHeaderHeading: "t2ExamPageHeaderHeading",
    themeTotalExamContainer: "t2TotalExamContainer",
    themeLanding_branch_box_li_buttons: "t2Landing_branch_box_li_buttons",

    // our courses container
    themeOurCoursesContainer: "t2OurCoursesContainer",
    themeCoursesHeadding: "t2CoursesHeadding",
    themeCoursesSubContainer: "t2CoursesSubContainer",
    themeCoursesUl: "t2CoursesUl",
    themeCourseLi: "t2CourseLi",
    themePortalName: "t2PortalName",
    themeExamsNames: "t2ExamsNames",
    themeFeaturesContainer: "t2FeaturesContainer",
    themeFeatures: "t2Features",
    themeFeatureImgC: "t2FeatureImgC",
    themeCourseName: "t2CourseName",
    themeFeaturesSecondContainer: "t2FeaturesSecondContainer",
    themeFeaturesToBeRow: "t2FeaturesToBeRow",
    themeArrowWithFeatures: "t2ArrowWithFeatures",
    themeUgHomePageFirstContainer: "t2UgHomePageFirstContainer",
    // missing classes
    themeCoursePortalNameImageContainer: "t2CoursePortalNameImageContainer",
    themeFeaturesHeading: "t2FeaturesHeading",
    // EXPLORE EXAM CLASSES
    themeExploreExamsMainContainer: "t2ExploreExamsMainContainer",
    themeExploreExamsSubContainer: "t2ExploreExamsSubContainer",
    themeNewExploreExams_ExamCard_MainContainer:
      "t2NewExploreExams_ExamCard_Container",
    themeNewExploreExams_ExamCard_Container:
      "t2NewExploreExams_ExamCard_Container",
    themeNewExploreExams_ExamName_Container:
      "t2NewExploreExams_ExamName_Container",
    themeNewExploreExams_PortalNames_Container:
      "t2NewExploreExams_PortalNames_Container",
    themeNewExploreExams_Image: "t2NewExploreExams_Image_Container",
    themeNewExploreExams_EachCard_Container:
      "t2NewExploreExams_EachCard_Container",
    themeLinkToSpecificExam: "t2LinkToSpecificExam",
    themeEEContainerForCards: "t2EEContainerForCards",
    // exam page classes
    themeExamInfoMainContainer: "t2ExamInfoMainContainer",
    themeExamInfoBtnsContainer: "t2ExamInfoBtnsContainer",
    themeExamInfoSubContainer: "t2ExamInfoSubContainer",
    themeExamInfoBtns: "t2ExamInfoBtns",
    themeExamInfoDivs: "t2ExamInfoDivs",
    themeExamInfoToggles: "t2ExamInfoToggles",
    themeToggles: "t2Toggles",
    // 2nd part
    themeExamCoursesContainer: "t2ExamCoursesContainer",
    themeExamCoursesSubContainer: "t2ExamCoursesSubContainer",
    themeExamCoursesNameHeading: "t2ExamCoursesNameHeading",
    themePortalNames: "t2PortalNames",
    themeExamPortalBtn: "t2ExamPortalBtn",
    themeExamPortalImgDivInCard: "t2ExamPortalImgDivInCard",
    // for footer, json classes
    themeFooterMainContainer: "t2FooterMainContainer",
    themeFooterSubContainer: "t2FooterSubContainer",
    themeFooterContentMainContainer: "t2FooterContentMainContainer",
    themeFooterFirstContentContainer: "t2FooterFirstContentContainer",
    themeFootereGRADTtutoContent: "t2FootereGRADTtutoContent",
    themeFooterFirstContent: "t2FooterFirstContentD",
    themeFooterLinksContent: "t2FooterLinksContent",
    themeFooterContactUsContent: "t2FooterContactUsContent",
    themeFooterContactData: "t2FooterContactData",
    themeFooterCopywriteContentContainer: "t2FooterCopywriteContentContainer",

    themeFooterCopywriteContent: "t2FooterCopywriteContent",
    // contact us classes for the div structure that i am decided
    themeCULogoContainer: "t2CULogoContainer",
    // about us classes
    themeAboutUsImgWithTextDiv: "t2AboutUsImgWithTextDiv",
    themeAUHeadingContainer: "t2AUHeadingContainer",
    themeAUSection1: "t2AUSection1",
    themeAUCapImgDiv: "t2AUCapImgDiv",
    themeVMContainer: "t2VMContainer",
    themeSpanLines: "t2SpanLines",
    themeVMText: "t2VMText",
    themeAUSectionPC: "t2AUSectionPC",
    themeAboutUsMainContainer: "t2AboutUsMainContainer",
    themeAUDataContainer: "t2AUDataContainer",
    themeAUSubContainer: "t2AUSubContainer",
    themeAUContentContainer: "t2AUContentContainer",
    themeAUImgDataContentContainer: "t2AUImgDataContentContainer",
    themeAUVMPC: "t2AUVMPC",
    themeAUVisionContent: "t2AUVisionContent",
    // contact us classes
    themeCUsMapContainer: "t2CUsMapContainer",
    themeCUFormContainer: "themeCUFormContainer",
    themeCUForm: "t2CUForm",
    themeCUParentContainer: "t2CUParentContainer",
    themeCUMapContainer: "t2CUMapContainer",
    themeContactUsMainContainer: "t2ContactUsMainContainer",
    themeCUMapDiv: "t2CUMapDiv",
    themeFormNdCardPC: "t2FormNdCardPC",
    themeFormNdCardSubContainer: "t2FormNdCardSubContainer",
    themeCUSubmitButtonDiv: "t2CUSubmitButtonDiv",
    themeFooterSMIcons: "t2FooterSMIcons",
    // theme orange classes for the course pasge
    // id: "quizHomeOrange",
    theme_COURSES: "orangeCOURSES",
    themeSectionContainer: "orangeSectionContainer",
    themeHeader: "orangeHeader",
    themeContant: "orangeContant",
    themeContainer: "orangeContainer",
    theme_courses_container: "orange_courses_container",
    // headerComponent: <Theme_GreenHeader />,
    themeCards: "orangeCards",
    themeLogin_btn: "orange_login_btn",
    theme_Dropdownmenu: "orange_Dropdownmenu",
    themeMainPageNavbar: "orangeThemeMainPageNavbar",
    theam_NavContant: "orange_NavContant",
    theme_portal: "orange_portal green_portal2",
    theme_examName: "orange_examName",
    theme_exam_group: "orange_exam_group",
    themeCard: "orangeCard",
    themeCardImg: "orangeImgDiv",
    themeCardBody: "orangeCardBody",
    themeCourseInfoSpan: "orangeThemeCourseInfo",
    themeCourseNameInCard: "orangeCourseNameInCard",
    // themeParentContainer:'',orange
    themeParentContainer: "orangeParentContainer",
    themeWCUContainer: "orangeWCUContainer",
    themeIconsAndCardsPC: "orangeIconsAndCardsPC",
    themeIconsAndCards: "orangeIconAndCards",

    // link classes
    LinksPagesMainContainer: "t2LinksPa1gesMainContainer",
    AboutUsImgContainer: "t2AboutUsImgContainer",
    LinksDataContainer: "t2LinksDataContainer",

    // FAQ classes
    FaqMainContainer: "t2FaqMainContainer",
    AboutUsImgContainer: "t2AboutUsImgContainer",
    FaqSubContainer: "t2FaqSubContainer",
    FaqDataContainer: "t2FaqDataContainer",
    FaqData: "t2FaqData",
    // course page classes
    // course page header classes
    themeCoursePageHeaderContainer: "t2CoursePageHeaderContainer",
    themeCPHeaderUl: "t2CPHeaderUl",
    ribbonInCP:"ribbonInCP",
    buttonInCP:"buttonInCP",
    ribbonContainerInCP:"ribbonContainerInCP",
    themeHeadingInCp:"t2HeadingInCp",

    // Popular Courses 
    themeBuyButtonInCP:"t2BuyButtonInCP",
    themePopularCourses_container:"t2PopularCourses_container",
    themePopularCourses_Subcontainer:"t2PopularCourses_Subcontainer",
    themeCourseheader_continer:"t2Courseheader_continer",
    theme_COURSES:"theme_COURSES",
    themeBuyCourseSpan:"t2BuyCourseSpan",
    themeTabsDivMainContainer:"t2TabsDivMainContainer",
    themeTabsDiv:"t2TabsDiv",
    themeTabsSubContainer:"t2TabsSubContainer",
    themeTabsButtonContainer:"t2TabsButtonContainer",
    themeTabButtonUl:"t2TabButtonUl",
    themeSelectedTabContentDiv:"t2SelectedTabContentDiv",
    themeTabsChange:"t2TabsChange",
    themeTabDetailsDiv:"t2TabDetailsDiv",
    themeTabDetailsSubDiv:"t2TabDetailsSubDiv",
    themeTabImageDiv:"t2TabImageDiv",
    themeTabContentDiv:"t2TabContentDiv",
    themeSelectedTabContentDiv:"t2SelectedTabContentDiv",
    themeTabContentSplittedText:"t2TabContentSplittedText",
    themeCardsToBeFlexed:"t2CardsToBeFlexed",
    
  },
};

export default JSONClasses;
// main file i think sooooooo
